name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch: # Allow manual trigger from GitHub interface

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Retrieve the repository code
      - name: Checkout code
        uses: actions/checkout@v4.1.0

      # 2. Set up Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Install dependencies and compile the project
      - name: Install dependencies and compile
        run: mvn clean compile

      # 4. Run unit tests and verification (excluding performance tests)
      - name: Run tests without performance tests
        run: mvn verify -Pskip-performance-tests

      # 5. Build the JAR artifact
      - name: Build jar
        run: mvn clean package

      # 6. Upload the artifact for other jobs
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: tourguide-jar
          path: target/*.jar
