name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Retrieve the repository code
      - name: Checkout code
        uses: actions/checkout@v4.1.0

      # 2. Set up Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Install local dependencies (required `.jar` files)
      - name: Install local dependencies
        run: |
          mvn install:install-file -Dfile=TourGuide/libs/gpsUtil.jar -DgroupId=gpsUtil -DartifactId=gpsUtil -Dversion=1.0.0 -Dpackaging=jar
          mvn install:install-file -Dfile=TourGuide/libs/RewardCentral.jar -DgroupId=rewardCentral -DartifactId=rewardCentral -Dversion=1.0.0 -Dpackaging=jar
          mvn install:install-file -Dfile=TourGuide/libs/TripPricer.jar -DgroupId=tripPricer -DartifactId=tripPricer -Dversion=1.0.0 -Dpackaging=jar

      # 4. Install dependencies and compile the project
      - name: Install dependencies and compile
        working-directory: TourGuide
        run: mvn clean compile

      # 5. Run unit tests and verification (excluding performance tests)
      - name: Run tests without performance tests
        working-directory: TourGuide
        run: mvn verify -Pskip-performance-tests

      # 6. Build the JAR artifact
      - name: Build jar
        working-directory: TourGuide
        run: mvn clean package

      # 7. Upload the artifact for other jobs
      - name: Move artifact to root-level target directory
        uses: actions/upload-artifact@v3
        with:
          name: tourguide-jar
          path: TourGuide/target/*.jar
